version: "3.8"

services:
  web:
    image: nginx:1.25-alpine
    user: nginx
    ports:
      - "127.0.0.1:8081:80"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 128M
